/*
 * This source file was generated by the Gradle 'init' task
 */
package org.quotely;

import org.quotely.forismatic.ForismaticClient;
import org.quotely.model.ForismaticQuote;
import org.quotely.model.ForismaticRequest;
import org.quotely.model.Lang;

public class QuotelyApp {
    public static void main(String[] args) {
        QuotelyApp quotely = new QuotelyApp();
        if (args.length == 0) {
            System.err.println("Usage: quotely <language_code>");
            return;
        }

        String languageCode = args[0];
        String quote = quotely.generateQuote(languageCode);

        System.out.println(quote);

        quotely.close();
    }

    private final ForismaticClient forismaticClient;

    public QuotelyApp() {
        forismaticClient = new ForismaticClient();
    }

    public ForismaticRequest parseLanguage(String languageCode) {
        Lang lang;
        try {
            lang = Lang.valueOf(languageCode);
        } catch (IllegalArgumentException iae) {
            throw new RuntimeException(String.format("Language %s not supported", languageCode));
        }
        return new ForismaticRequest(lang);
    }

    public String generateQuote(String languageCode) {
        ForismaticRequest forismaticRequest = parseLanguage(languageCode);
        ForismaticQuote forismaticQuote = forismaticClient.getForismaticQuote(forismaticRequest);
        return forismaticQuote.quoteText();
    }

    public void close() {
        forismaticClient.close();
    }
}
