/*
 * This source file was generated by the Gradle 'init' task
 */
package org.quotely;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.quotely.model.Lang;

class QuotelyTest {
    private QuotelyApp quotely = new QuotelyApp();

    @ParameterizedTest
    @EnumSource(Lang.class)
    public void testGenerateQuote(Lang lang) {
        String quote = quotely.generateQuote(lang.name());
        Assertions.assertNotNull(quote);
        System.err.println(quote);
    }

    @Test
    public void testInvalidLanguage() {
        String languageCode = "es";
        Assertions.assertThrows(RuntimeException.class, () -> {
            quotely.generateQuote(languageCode);
        });
    }
}
